// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/orchestration.proto

package orchestration

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestrationService_RegisterAgent_FullMethodName    = "/orchestration.OrchestrationService/RegisterAgent"
	OrchestrationService_UnregisterAgent_FullMethodName  = "/orchestration.OrchestrationService/UnregisterAgent"
	OrchestrationService_Heartbeat_FullMethodName        = "/orchestration.OrchestrationService/Heartbeat"
	OrchestrationService_OpenConversation_FullMethodName = "/orchestration.OrchestrationService/OpenConversation"
	OrchestrationService_SendInstruction_FullMethodName  = "/orchestration.OrchestrationService/SendInstruction"
	OrchestrationService_ReportCompletion_FullMethodName = "/orchestration.OrchestrationService/ReportCompletion"
)

// OrchestrationServiceClient is the client API for OrchestrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI-Native OrchestrationService for event-driven agent communication
// This service is designed for AI-first, conversational agent orchestration
type OrchestrationServiceClient interface {
	// Agent lifecycle management
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	UnregisterAgent(ctx context.Context, in *UnregisterAgentRequest, opts ...grpc.CallOption) (*UnregisterAgentResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// AI-native conversational communication
	OpenConversation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConversationMessage, ConversationMessage], error)
	SendInstruction(ctx context.Context, in *InstructionMessage, opts ...grpc.CallOption) (*InstructionResponse, error)
	ReportCompletion(ctx context.Context, in *CompletionMessage, opts ...grpc.CallOption) (*CompletionResponse, error)
}

type orchestrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestrationServiceClient(cc grpc.ClientConnInterface) OrchestrationServiceClient {
	return &orchestrationServiceClient{cc}
}

func (c *orchestrationServiceClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, OrchestrationService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationServiceClient) UnregisterAgent(ctx context.Context, in *UnregisterAgentRequest, opts ...grpc.CallOption) (*UnregisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterAgentResponse)
	err := c.cc.Invoke(ctx, OrchestrationService_UnregisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, OrchestrationService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationServiceClient) OpenConversation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConversationMessage, ConversationMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestrationService_ServiceDesc.Streams[0], OrchestrationService_OpenConversation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConversationMessage, ConversationMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestrationService_OpenConversationClient = grpc.BidiStreamingClient[ConversationMessage, ConversationMessage]

func (c *orchestrationServiceClient) SendInstruction(ctx context.Context, in *InstructionMessage, opts ...grpc.CallOption) (*InstructionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstructionResponse)
	err := c.cc.Invoke(ctx, OrchestrationService_SendInstruction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationServiceClient) ReportCompletion(ctx context.Context, in *CompletionMessage, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, OrchestrationService_ReportCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestrationServiceServer is the server API for OrchestrationService service.
// All implementations must embed UnimplementedOrchestrationServiceServer
// for forward compatibility.
//
// AI-Native OrchestrationService for event-driven agent communication
// This service is designed for AI-first, conversational agent orchestration
type OrchestrationServiceServer interface {
	// Agent lifecycle management
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	UnregisterAgent(context.Context, *UnregisterAgentRequest) (*UnregisterAgentResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// AI-native conversational communication
	OpenConversation(grpc.BidiStreamingServer[ConversationMessage, ConversationMessage]) error
	SendInstruction(context.Context, *InstructionMessage) (*InstructionResponse, error)
	ReportCompletion(context.Context, *CompletionMessage) (*CompletionResponse, error)
	mustEmbedUnimplementedOrchestrationServiceServer()
}

// UnimplementedOrchestrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestrationServiceServer struct{}

func (UnimplementedOrchestrationServiceServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedOrchestrationServiceServer) UnregisterAgent(context.Context, *UnregisterAgentRequest) (*UnregisterAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterAgent not implemented")
}
func (UnimplementedOrchestrationServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedOrchestrationServiceServer) OpenConversation(grpc.BidiStreamingServer[ConversationMessage, ConversationMessage]) error {
	return status.Errorf(codes.Unimplemented, "method OpenConversation not implemented")
}
func (UnimplementedOrchestrationServiceServer) SendInstruction(context.Context, *InstructionMessage) (*InstructionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInstruction not implemented")
}
func (UnimplementedOrchestrationServiceServer) ReportCompletion(context.Context, *CompletionMessage) (*CompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportCompletion not implemented")
}
func (UnimplementedOrchestrationServiceServer) mustEmbedUnimplementedOrchestrationServiceServer() {}
func (UnimplementedOrchestrationServiceServer) testEmbeddedByValue()                              {}

// UnsafeOrchestrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestrationServiceServer will
// result in compilation errors.
type UnsafeOrchestrationServiceServer interface {
	mustEmbedUnimplementedOrchestrationServiceServer()
}

func RegisterOrchestrationServiceServer(s grpc.ServiceRegistrar, srv OrchestrationServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrchestrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestrationService_ServiceDesc, srv)
}

func _OrchestrationService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServiceServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationService_UnregisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServiceServer).UnregisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationService_UnregisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServiceServer).UnregisterAgent(ctx, req.(*UnregisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationService_OpenConversation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrchestrationServiceServer).OpenConversation(&grpc.GenericServerStream[ConversationMessage, ConversationMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestrationService_OpenConversationServer = grpc.BidiStreamingServer[ConversationMessage, ConversationMessage]

func _OrchestrationService_SendInstruction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstructionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServiceServer).SendInstruction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationService_SendInstruction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServiceServer).SendInstruction(ctx, req.(*InstructionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationService_ReportCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServiceServer).ReportCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationService_ReportCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServiceServer).ReportCompletion(ctx, req.(*CompletionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestrationService_ServiceDesc is the grpc.ServiceDesc for OrchestrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestration.OrchestrationService",
	HandlerType: (*OrchestrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _OrchestrationService_RegisterAgent_Handler,
		},
		{
			MethodName: "UnregisterAgent",
			Handler:    _OrchestrationService_UnregisterAgent_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _OrchestrationService_Heartbeat_Handler,
		},
		{
			MethodName: "SendInstruction",
			Handler:    _OrchestrationService_SendInstruction_Handler,
		},
		{
			MethodName: "ReportCompletion",
			Handler:    _OrchestrationService_ReportCompletion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenConversation",
			Handler:       _OrchestrationService_OpenConversation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/orchestration.proto",
}
