// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/orchestration.proto

package orchestration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums for AI-native communication
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNKNOWN       AgentStatus = 0
	AgentStatus_AGENT_STATUS_HEALTHY       AgentStatus = 1
	AgentStatus_AGENT_STATUS_BUSY          AgentStatus = 2
	AgentStatus_AGENT_STATUS_ERROR         AgentStatus = 3
	AgentStatus_AGENT_STATUS_SHUTTING_DOWN AgentStatus = 4
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNKNOWN",
		1: "AGENT_STATUS_HEALTHY",
		2: "AGENT_STATUS_BUSY",
		3: "AGENT_STATUS_ERROR",
		4: "AGENT_STATUS_SHUTTING_DOWN",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNKNOWN":       0,
		"AGENT_STATUS_HEALTHY":       1,
		"AGENT_STATUS_BUSY":          2,
		"AGENT_STATUS_ERROR":         3,
		"AGENT_STATUS_SHUTTING_DOWN": 4,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_orchestration_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_api_proto_orchestration_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNKNOWN       MessageType = 0
	MessageType_MESSAGE_TYPE_INSTRUCTION   MessageType = 1 // AI → Agent: Natural language instruction
	MessageType_MESSAGE_TYPE_COMPLETION    MessageType = 2 // Agent → AI: Task completion response
	MessageType_MESSAGE_TYPE_STATUS_UPDATE MessageType = 3 // Agent status updates
	MessageType_MESSAGE_TYPE_ERROR         MessageType = 4 // Error notifications
	MessageType_MESSAGE_TYPE_HEARTBEAT     MessageType = 5 // Keep-alive messages
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNKNOWN",
		1: "MESSAGE_TYPE_INSTRUCTION",
		2: "MESSAGE_TYPE_COMPLETION",
		3: "MESSAGE_TYPE_STATUS_UPDATE",
		4: "MESSAGE_TYPE_ERROR",
		5: "MESSAGE_TYPE_HEARTBEAT",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNKNOWN":       0,
		"MESSAGE_TYPE_INSTRUCTION":   1,
		"MESSAGE_TYPE_COMPLETION":    2,
		"MESSAGE_TYPE_STATUS_UPDATE": 3,
		"MESSAGE_TYPE_ERROR":         4,
		"MESSAGE_TYPE_HEARTBEAT":     5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_orchestration_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_api_proto_orchestration_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{1}
}

// Agent registration - simplified for AI-native approach
type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Capabilities  []*AgentCapability     `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_api_proto_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterAgentRequest) GetCapabilities() []*AgentCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_api_proto_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterAgentResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterAgentResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

// Agent capabilities - what the agent can do
type AgentCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // e.g., "word-count", "text-analysis"
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Human-readable description for AI
	Inputs        []string               `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`           // Expected input types
	Outputs       []string               `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`         // Expected output types
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCapability) Reset() {
	*x = AgentCapability{}
	mi := &file_api_proto_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapability) ProtoMessage() {}

func (x *AgentCapability) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapability.ProtoReflect.Descriptor instead.
func (*AgentCapability) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *AgentCapability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentCapability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentCapability) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *AgentCapability) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// Heartbeat - simple health check
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        AgentStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=orchestration.AgentStatus" json:"status,omitempty"`
	HealthMetrics *structpb.Struct       `protobuf:"bytes,4,opt,name=health_metrics,json=healthMetrics,proto3" json:"health_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_orchestration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNKNOWN
}

func (x *HeartbeatRequest) GetHealthMetrics() *structpb.Struct {
	if x != nil {
		return x.HealthMetrics
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_orchestration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Agent unregistration
type UnregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentRequest) Reset() {
	*x = UnregisterAgentRequest{}
	mi := &file_api_proto_orchestration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentRequest) ProtoMessage() {}

func (x *UnregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UnregisterAgentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UnregisterAgentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentResponse) Reset() {
	*x = UnregisterAgentResponse{}
	mi := &file_api_proto_orchestration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentResponse) ProtoMessage() {}

func (x *UnregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*UnregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{6}
}

func (x *UnregisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConversationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	FromId        string                 `protobuf:"bytes,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"` // agent_id or "orchestrator"
	ToId          string                 `protobuf:"bytes,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`       // agent_id or "orchestrator"
	Type          MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=orchestration.MessageType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"` // Natural language instruction or response
	Context       *structpb.Struct       `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationMessage) Reset() {
	*x = ConversationMessage{}
	mi := &file_api_proto_orchestration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessage) ProtoMessage() {}

func (x *ConversationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessage.ProtoReflect.Descriptor instead.
func (*ConversationMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{7}
}

func (x *ConversationMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ConversationMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ConversationMessage) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *ConversationMessage) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *ConversationMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *ConversationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConversationMessage) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ConversationMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// AI sends natural language instructions to agents
type InstructionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstructionId string                 `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`       // Natural language instruction from AI
	Capability    string                 `protobuf:"bytes,5,opt,name=capability,proto3" json:"capability,omitempty"` // Which agent capability to use
	Parameters    *structpb.Struct       `protobuf:"bytes,6,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructionMessage) Reset() {
	*x = InstructionMessage{}
	mi := &file_api_proto_orchestration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionMessage) ProtoMessage() {}

func (x *InstructionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionMessage.ProtoReflect.Descriptor instead.
func (*InstructionMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{8}
}

func (x *InstructionMessage) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *InstructionMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *InstructionMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InstructionMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InstructionMessage) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *InstructionMessage) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *InstructionMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type InstructionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	InstructionId string                 `protobuf:"bytes,3,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructionResponse) Reset() {
	*x = InstructionResponse{}
	mi := &file_api_proto_orchestration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionResponse) ProtoMessage() {}

func (x *InstructionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionResponse.ProtoReflect.Descriptor instead.
func (*InstructionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{9}
}

func (x *InstructionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstructionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstructionResponse) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *InstructionResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Agent reports completion with natural language response
type CompletionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompletionId  string                 `protobuf:"bytes,1,opt,name=completion_id,json=completionId,proto3" json:"completion_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	InstructionId string                 `protobuf:"bytes,3,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"` // Reference to the original instruction
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                               // Natural language response
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // If success = false
	ResultData    *structpb.Struct       `protobuf:"bytes,8,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionMessage) Reset() {
	*x = CompletionMessage{}
	mi := &file_api_proto_orchestration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionMessage) ProtoMessage() {}

func (x *CompletionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionMessage.ProtoReflect.Descriptor instead.
func (*CompletionMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{10}
}

func (x *CompletionMessage) GetCompletionId() string {
	if x != nil {
		return x.CompletionId
	}
	return ""
}

func (x *CompletionMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CompletionMessage) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *CompletionMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CompletionMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompletionMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompletionMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CompletionMessage) GetResultData() *structpb.Struct {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *CompletionMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CompletionId  string                 `protobuf:"bytes,3,opt,name=completion_id,json=completionId,proto3" json:"completion_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_api_proto_orchestration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestration_proto_rawDescGZIP(), []int{11}
}

func (x *CompletionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompletionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompletionResponse) GetCompletionId() string {
	if x != nil {
		return x.CompletionId
	}
	return ""
}

var File_api_proto_orchestration_proto protoreflect.FileDescriptor

const file_api_proto_orchestration_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/orchestration.proto\x12\rorchestration\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xec\x01\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12B\n" +
	"\fcapabilities\x18\x04 \x03(\v2\x1e.orchestration.AgentCapabilityR\fcapabilities\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xab\x01\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12?\n" +
	"\rregistered_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"y\n" +
	"\x0fAgentCapability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06inputs\x18\x03 \x03(\tR\x06inputs\x12\x18\n" +
	"\aoutputs\x18\x04 \x03(\tR\aoutputs\"\xc0\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.orchestration.AgentStatusR\x06status\x12>\n" +
	"\x0ehealth_metrics\x18\x04 \x01(\v2\x17.google.protobuf.StructR\rhealthMetrics\"\x84\x01\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"j\n" +
	"\x16UnregisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"M\n" +
	"\x17UnregisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc0\x02\n" +
	"\x13ConversationMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x17\n" +
	"\afrom_id\x18\x03 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x04 \x01(\tR\x04toId\x12.\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1a.orchestration.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x121\n" +
	"\acontext\x18\a \x01(\v2\x17.google.protobuf.StructR\acontext\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xaa\x02\n" +
	"\x12InstructionMessage\x12%\n" +
	"\x0einstruction_id\x18\x01 \x01(\tR\rinstructionId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"capability\x18\x05 \x01(\tR\n" +
	"capability\x127\n" +
	"\n" +
	"parameters\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x97\x01\n" +
	"\x13InstructionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0einstruction_id\x18\x03 \x01(\tR\rinstructionId\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\xee\x02\n" +
	"\x11CompletionMessage\x12#\n" +
	"\rcompletion_id\x18\x01 \x01(\tR\fcompletionId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12%\n" +
	"\x0einstruction_id\x18\x03 \x01(\tR\rinstructionId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x128\n" +
	"\vresult_data\x18\b \x01(\v2\x17.google.protobuf.StructR\n" +
	"resultData\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"m\n" +
	"\x12CompletionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rcompletion_id\x18\x03 \x01(\tR\fcompletionId*\x90\x01\n" +
	"\vAgentStatus\x12\x18\n" +
	"\x14AGENT_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14AGENT_STATUS_HEALTHY\x10\x01\x12\x15\n" +
	"\x11AGENT_STATUS_BUSY\x10\x02\x12\x16\n" +
	"\x12AGENT_STATUS_ERROR\x10\x03\x12\x1e\n" +
	"\x1aAGENT_STATUS_SHUTTING_DOWN\x10\x04*\xb6\x01\n" +
	"\vMessageType\x12\x18\n" +
	"\x14MESSAGE_TYPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18MESSAGE_TYPE_INSTRUCTION\x10\x01\x12\x1b\n" +
	"\x17MESSAGE_TYPE_COMPLETION\x10\x02\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_STATUS_UPDATE\x10\x03\x12\x16\n" +
	"\x12MESSAGE_TYPE_ERROR\x10\x04\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HEARTBEAT\x10\x052\xb7\x04\n" +
	"\x14OrchestrationService\x12Z\n" +
	"\rRegisterAgent\x12#.orchestration.RegisterAgentRequest\x1a$.orchestration.RegisterAgentResponse\x12`\n" +
	"\x0fUnregisterAgent\x12%.orchestration.UnregisterAgentRequest\x1a&.orchestration.UnregisterAgentResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.orchestration.HeartbeatRequest\x1a .orchestration.HeartbeatResponse\x12^\n" +
	"\x10OpenConversation\x12\".orchestration.ConversationMessage\x1a\".orchestration.ConversationMessage(\x010\x01\x12X\n" +
	"\x0fSendInstruction\x12!.orchestration.InstructionMessage\x1a\".orchestration.InstructionResponse\x12W\n" +
	"\x10ReportCompletion\x12 .orchestration.CompletionMessage\x1a!.orchestration.CompletionResponseB+Z)neuromesh/internal/api/grpc/orchestrationb\x06proto3"

var (
	file_api_proto_orchestration_proto_rawDescOnce sync.Once
	file_api_proto_orchestration_proto_rawDescData []byte
)

func file_api_proto_orchestration_proto_rawDescGZIP() []byte {
	file_api_proto_orchestration_proto_rawDescOnce.Do(func() {
		file_api_proto_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_orchestration_proto_rawDesc), len(file_api_proto_orchestration_proto_rawDesc)))
	})
	return file_api_proto_orchestration_proto_rawDescData
}

var file_api_proto_orchestration_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_orchestration_proto_goTypes = []any{
	(AgentStatus)(0),                // 0: orchestration.AgentStatus
	(MessageType)(0),                // 1: orchestration.MessageType
	(*RegisterAgentRequest)(nil),    // 2: orchestration.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),   // 3: orchestration.RegisterAgentResponse
	(*AgentCapability)(nil),         // 4: orchestration.AgentCapability
	(*HeartbeatRequest)(nil),        // 5: orchestration.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 6: orchestration.HeartbeatResponse
	(*UnregisterAgentRequest)(nil),  // 7: orchestration.UnregisterAgentRequest
	(*UnregisterAgentResponse)(nil), // 8: orchestration.UnregisterAgentResponse
	(*ConversationMessage)(nil),     // 9: orchestration.ConversationMessage
	(*InstructionMessage)(nil),      // 10: orchestration.InstructionMessage
	(*InstructionResponse)(nil),     // 11: orchestration.InstructionResponse
	(*CompletionMessage)(nil),       // 12: orchestration.CompletionMessage
	(*CompletionResponse)(nil),      // 13: orchestration.CompletionResponse
	(*structpb.Struct)(nil),         // 14: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
}
var file_api_proto_orchestration_proto_depIdxs = []int32{
	4,  // 0: orchestration.RegisterAgentRequest.capabilities:type_name -> orchestration.AgentCapability
	14, // 1: orchestration.RegisterAgentRequest.metadata:type_name -> google.protobuf.Struct
	15, // 2: orchestration.RegisterAgentResponse.registered_at:type_name -> google.protobuf.Timestamp
	0,  // 3: orchestration.HeartbeatRequest.status:type_name -> orchestration.AgentStatus
	14, // 4: orchestration.HeartbeatRequest.health_metrics:type_name -> google.protobuf.Struct
	15, // 5: orchestration.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	1,  // 6: orchestration.ConversationMessage.type:type_name -> orchestration.MessageType
	14, // 7: orchestration.ConversationMessage.context:type_name -> google.protobuf.Struct
	15, // 8: orchestration.ConversationMessage.timestamp:type_name -> google.protobuf.Timestamp
	14, // 9: orchestration.InstructionMessage.parameters:type_name -> google.protobuf.Struct
	15, // 10: orchestration.InstructionMessage.timestamp:type_name -> google.protobuf.Timestamp
	14, // 11: orchestration.CompletionMessage.result_data:type_name -> google.protobuf.Struct
	15, // 12: orchestration.CompletionMessage.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 13: orchestration.OrchestrationService.RegisterAgent:input_type -> orchestration.RegisterAgentRequest
	7,  // 14: orchestration.OrchestrationService.UnregisterAgent:input_type -> orchestration.UnregisterAgentRequest
	5,  // 15: orchestration.OrchestrationService.Heartbeat:input_type -> orchestration.HeartbeatRequest
	9,  // 16: orchestration.OrchestrationService.OpenConversation:input_type -> orchestration.ConversationMessage
	10, // 17: orchestration.OrchestrationService.SendInstruction:input_type -> orchestration.InstructionMessage
	12, // 18: orchestration.OrchestrationService.ReportCompletion:input_type -> orchestration.CompletionMessage
	3,  // 19: orchestration.OrchestrationService.RegisterAgent:output_type -> orchestration.RegisterAgentResponse
	8,  // 20: orchestration.OrchestrationService.UnregisterAgent:output_type -> orchestration.UnregisterAgentResponse
	6,  // 21: orchestration.OrchestrationService.Heartbeat:output_type -> orchestration.HeartbeatResponse
	9,  // 22: orchestration.OrchestrationService.OpenConversation:output_type -> orchestration.ConversationMessage
	11, // 23: orchestration.OrchestrationService.SendInstruction:output_type -> orchestration.InstructionResponse
	13, // 24: orchestration.OrchestrationService.ReportCompletion:output_type -> orchestration.CompletionResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_orchestration_proto_init() }
func file_api_proto_orchestration_proto_init() {
	if File_api_proto_orchestration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_orchestration_proto_rawDesc), len(file_api_proto_orchestration_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_orchestration_proto_goTypes,
		DependencyIndexes: file_api_proto_orchestration_proto_depIdxs,
		EnumInfos:         file_api_proto_orchestration_proto_enumTypes,
		MessageInfos:      file_api_proto_orchestration_proto_msgTypes,
	}.Build()
	File_api_proto_orchestration_proto = out.File
	file_api_proto_orchestration_proto_goTypes = nil
	file_api_proto_orchestration_proto_depIdxs = nil
}
